//! In-app Help (the embedded README, sectioned, with screenshots) + About
//! (version/build info and data locations). Everything is compiled into the
//! binary — the view works fully offline and never touches the repo checkout.

use super::*;

/// The full manual, embedded at compile time.
static README_MD: &str = include_str!("../../README.md");

// `HELP_IMAGES: &[(&str, &[u8])]` — the README's screenshots as raw PNG bytes
// keyed by `bytes://doc/screenshots/<name>.png` URIs (generated by build.rs).
include!(concat!(env!("OUT_DIR"), "/help_images.rs"));

/// One README section: an `##` or `###` heading and its body (which keeps any
/// `####` sub-headings inline).
pub(super) struct HelpSection {
    /// 1 = the synthetic "Overview" intro, 2 = `##`, 3 = `###`.
    pub level: u8,
    /// Heading text with markdown markup stripped, for the TOC.
    pub title: String,
    /// Body slice of [`README_MD`] (includes the heading line).
    pub body: &'static str,
}

/// Help/About view state, built once on first open.
pub(super) struct HelpState {
    pub sections: Vec<HelpSection>,
    /// TOC selection: 0 = About (synthetic), `i >= 1` = `sections[i - 1]`.
    pub selected: usize,
    /// `#slug` → selected-index, for in-app anchor navigation. Includes
    /// `####` headings (mapped to their enclosing section).
    anchor_to_section: std::collections::HashMap<String, usize>,
    md_cache: egui_commonmark::CommonMarkCache,
    filter: String,
    scroll_to_top: bool,
    images_registered: bool,
}

impl Default for HelpState {
    fn default() -> Self {
        let (sections, anchors) = parse_sections(README_MD);
        let mut md_cache = egui_commonmark::CommonMarkCache::default();
        // Registering an anchor as a link hook stops the viewer from trying
        // to open it as a URL; we poll the hook after each render instead.
        for anchor in anchors.keys() {
            md_cache.add_link_hook(anchor.clone());
        }
        // The one relative repo link in the README — a deliberate no-op
        // in-app (there is nothing sensible to open).
        md_cache.add_link_hook("../yt-websub");
        HelpState {
            sections,
            selected: 1, // Overview
            anchor_to_section: anchors,
            md_cache,
            filter: String::new(),
            scroll_to_top: false,
            images_registered: false,
        }
    }
}

/// GitHub-style heading slug: lowercase; spaces become `-`; `[a-z0-9_-]` kept;
/// everything else (punctuation, `**`, emoji) dropped. Verified against the
/// anchors GitHub generates for this README.
pub(super) fn github_slug(heading: &str) -> String {
    let mut s = String::with_capacity(heading.len());
    for c in heading.trim().chars() {
        let c = c.to_ascii_lowercase();
        match c {
            ' ' => s.push('-'),
            'a'..='z' | '0'..='9' | '_' | '-' => s.push(c),
            _ => {}
        }
    }
    s
}

/// Strip the markdown markup that appears in this README's headings so TOC
/// entries read clean ("I/O monitor (the I/O tab)").
fn strip_md_markup(title: &str) -> String {
    title.replace("**", "").replace('`', "").trim().to_string()
}

/// Split the README into `##`/`###` sections (fence-aware, so a `## ` inside
/// a code block never fakes a heading) and build the anchor map, including
/// `####` headings which resolve to their enclosing section. Returns
/// `(sections, anchor → selected-index)` where selected-index 0 is reserved
/// for About and section `i` maps to `i + 1`.
#[allow(clippy::type_complexity)]
pub(super) fn parse_sections(
    md: &'static str,
) -> (Vec<HelpSection>, std::collections::HashMap<String, usize>) {
    let mut sections: Vec<HelpSection> = Vec::new();
    let mut anchors: std::collections::HashMap<String, usize> = Default::default();
    let mut slug_counts: std::collections::HashMap<String, usize> = Default::default();
    // Register `slug` (deduped GitHub-style with -1/-2 suffixes) for the
    // section at `sel` unless already claimed by an earlier heading.
    let mut add_anchor =
        |anchors: &mut std::collections::HashMap<String, usize>, title: &str, sel: usize| {
            let base = github_slug(title);
            let n = slug_counts.entry(base.clone()).or_insert(0);
            let slug = if *n == 0 { base.clone() } else { format!("{base}-{n}") };
            *n += 1;
            anchors.insert(format!("#{slug}"), sel);
        };

    let mut in_fence = false;
    let mut cur_start = 0usize; // byte offset of the current section's start
    let mut cur_level = 1u8;
    let mut cur_title = "Overview".to_string();
    let close =
        |sections: &mut Vec<HelpSection>, start: usize, end: usize, level: u8, title: &str| {
            let body = md[start..end].trim_end();
            if !body.is_empty() || level == 1 {
                sections.push(HelpSection {
                    level,
                    title: strip_md_markup(title),
                    body,
                });
            }
        };

    let mut offset = 0usize;
    for line in md.split_inclusive('\n') {
        let trimmed = line.trim_end();
        if trimmed.trim_start().starts_with("```") {
            in_fence = !in_fence;
        }
        if !in_fence {
            let (level, title) = if let Some(t) = trimmed.strip_prefix("### ") {
                (3u8, t)
            } else if let Some(t) = trimmed.strip_prefix("## ") {
                (2u8, t)
            } else if let Some(t) = trimmed.strip_prefix("#### ") {
                // Stays inside the current section, but is a valid anchor
                // target (two README links point at #### headings). The
                // enclosing section is still open — it will be pushed at
                // index `sections.len()`, i.e. selected `len + 1`.
                add_anchor(&mut anchors, t, sections.len() + 1);
                (0, "")
            } else if let Some(t) = trimmed.strip_prefix("# ") {
                // The top-level title — part of Overview, but anchorable.
                add_anchor(&mut anchors, t, 1);
                (0, "")
            } else {
                (0, "")
            };
            if level > 0 {
                close(&mut sections, cur_start, offset, cur_level, &cur_title);
                cur_start = offset;
                cur_level = level;
                cur_title = title.to_string();
                // The new section will be pushed at index `sections.len()`
                // (the previous one was just closed) → selected `len + 1`.
                add_anchor(&mut anchors, title, sections.len() + 1);
            }
        }
        offset += line.len();
    }
    close(&mut sections, cur_start, md.len(), cur_level, &cur_title);
    (sections, anchors)
}

impl StreamArchiverApp {
    /// The Help view: About + the sectioned README with a TOC sidebar.
    pub(super) fn help_view(&mut self, ui: &mut egui::Ui) {
        let state = self.help.get_or_insert_default();
        if !state.images_registered {
            for (uri, bytes) in HELP_IMAGES {
                ui.ctx().include_bytes(*uri, *bytes);
            }
            state.images_registered = true;
        }

        egui::Panel::left("help_toc")
            .resizable(true)
            .default_size(240.0)
            .show_inside(ui, |ui| {
                ui.add_space(4.0);
                ui.horizontal(|ui| {
                    ui.add(
                        egui::TextEdit::singleline(&mut state.filter)
                            .hint_text("Filter sections…")
                            .desired_width(ui.available_width() - 24.0),
                    )
                    .on_hover_text("Show only sections whose title matches.");
                    if !state.filter.is_empty()
                        && ui.button("✕").on_hover_text("Clear filter").clicked()
                    {
                        state.filter.clear();
                    }
                });
                ui.separator();
                let q = state.filter.trim().to_lowercase();
                egui::ScrollArea::vertical().auto_shrink([false, false]).show(ui, |ui| {
                    if (q.is_empty() || "about".contains(&q))
                        && ui
                            .selectable_label(state.selected == 0, "ℹ About")
                            .on_hover_text(
                                "Version, build and commit info, and where this app \
                                 keeps its data.",
                            )
                            .clicked()
                    {
                        state.selected = 0;
                    }
                    for (i, s) in state.sections.iter().enumerate() {
                        if !q.is_empty() && !s.title.to_lowercase().contains(&q) {
                            continue;
                        }
                        let mut rich = egui::RichText::new(&s.title);
                        if s.level <= 2 {
                            rich = rich.strong();
                        }
                        let resp = ui
                            .horizontal(|ui| {
                                if s.level == 3 {
                                    ui.add_space(16.0);
                                }
                                ui.selectable_label(state.selected == i + 1, rich)
                            })
                            .inner
                            .on_hover_text("Open this section of the manual.");
                        if resp.clicked() {
                            state.selected = i + 1;
                            state.scroll_to_top = true;
                        }
                    }
                });
            });

        egui::CentralPanel::default().show_inside(ui, |ui| {
            if state.selected == 0 {
                about_panel(ui);
                return;
            }
            let Some(section) = state.sections.get(state.selected - 1) else {
                state.selected = 1;
                return;
            };
            let mut sa = egui::ScrollArea::vertical()
                .auto_shrink([false, false])
                .id_salt(("help_body", state.selected));
            if state.scroll_to_top {
                sa = sa.vertical_scroll_offset(0.0);
                state.scroll_to_top = false;
            }
            sa.show(ui, |ui| {
                ui.push_id(("help_md", state.selected), |ui| {
                    egui_commonmark::CommonMarkViewer::new()
                        .default_implicit_uri_scheme("bytes://")
                        .max_image_width(Some(1000))
                        .show_alt_text_on_hover(true)
                        .show(ui, &mut state.md_cache, section.body);
                });
            });
            // Poll AFTER show: hooks are reset at the start of the next show,
            // so a clicked internal anchor is visible right here this frame.
            let mut jump: Option<usize> = None;
            for (anchor, &idx) in &state.anchor_to_section {
                if state.md_cache.get_link_hook(anchor) == Some(true) {
                    jump = Some(idx);
                }
            }
            if let Some(idx) = jump {
                state.selected = idx.min(state.sections.len());
                state.scroll_to_top = true;
            }
        });
    }
}

/// The About panel: identity of the running build plus every place the app
/// keeps data, with open/copy buttons. (This is the info the top bar's old
/// version label and its hover used to show.)
fn about_panel(ui: &mut egui::Ui) {
    let built_full = env!("BUILD_UNIX")
        .parse::<i64>()
        .ok()
        .and_then(|s| chrono::DateTime::from_timestamp(s, 0))
        .map(|dt| dt.with_timezone(&chrono::Local).format("%Y-%m-%d %H:%M:%S").to_string())
        .unwrap_or_default();
    egui::ScrollArea::vertical().auto_shrink([false, false]).show(ui, |ui| {
        ui.add_space(8.0);
        ui.heading("StreamArchiver");
        ui.add_space(4.0);
        egui::Grid::new("about_build").num_columns(2).spacing([16.0, 4.0]).show(ui, |ui| {
            ui.label("Version:");
            ui.monospace(format!("v{}", env!("APP_VERSION")))
                .on_hover_text("Major.minor from Cargo.toml; patch is a local build counter.");
            ui.end_row();
            ui.label("Build:");
            ui.monospace(format!("#{}", env!("BUILD_NUMBER")))
                .on_hover_text("Total commit count at build time.");
            ui.end_row();
            ui.label("Commit:");
            ui.monospace(env!("GIT_HASH"))
                .on_hover_text("Git commit this binary was built from (-dirty = uncommitted changes).");
            ui.end_row();
            ui.label("Compiled:");
            ui.monospace(&built_full).on_hover_text("When this binary was compiled (local time).");
            ui.end_row();
        });
        ui.add_space(6.0);
        if ui
            .button("🗐 Copy build info")
            .on_hover_text("Copy version, build number, commit and compile time — paste into bug reports.")
            .clicked()
        {
            ui.ctx().copy_text(format!(
                "StreamArchiver v{} · build {}\ncommit {}\ncompiled {built_full}",
                env!("APP_VERSION"),
                env!("BUILD_NUMBER"),
                env!("GIT_HASH"),
            ));
        }

        ui.add_space(12.0);
        ui.strong("Data locations");
        ui.add_space(4.0);
        // (label, path, points-at-a-file, hover) — file rows open their parent
        // folder; deciding statically avoids a render-path fs probe.
        let rows: [(&str, std::path::PathBuf, bool, &str); 5] = [
            ("Data dir", crate::app_paths::data_dir(), false, "Settings, database, and app state."),
            ("Database", crate::app_paths::db_path(), true, "The SQLite database (recordings, channels, history)."),
            ("Logs", crate::app_paths::logs_dir(), false, "App log + per-capture tool logs (logs\\captures\\)."),
            ("Asset cache", crate::app_paths::asset_cache_dir(), false, "Channel icons, banners, emotes, posts, About snapshots."),
            ("Default output", crate::app_paths::default_output_dir(), false, "Where recordings land unless a channel/instance overrides it."),
        ];
        egui::Grid::new("about_paths").num_columns(3).spacing([12.0, 4.0]).show(ui, |ui| {
            for (label, path, is_file, hover) in &rows {
                ui.label(*label).on_hover_text(*hover);
                ui.monospace(path.display().to_string());
                ui.horizontal(|ui| {
                    if ui.button("📂").on_hover_text("Open in file explorer").clicked() {
                        let target: &std::path::Path =
                            if *is_file { path.parent().unwrap_or(path) } else { path };
                        crate::platform::open_path(target);
                    }
                    if ui.button("🗐").on_hover_text("Copy path").clicked() {
                        ui.ctx().copy_text(path.display().to_string());
                    }
                });
                ui.end_row();
            }
        });
    });
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn slugs_match_github_anchors() {
        // Real headings from the README vs the anchors GitHub generates.
        let cases = [
            ("Twitch VOD recovery (deleted & muted VODs)", "twitch-vod-recovery-deleted--muted-vods"),
            ("YouTube live capture-from-start (SABR)", "youtube-live-capture-from-start-sabr"),
            ("Audio & subtitle tracks", "audio--subtitle-tracks"),
            ("I/O monitor (the **I/O** tab)", "io-monitor-the-io-tab"),
            ("Watching SABR captures & live-edge previews", "watching-sabr-captures--live-edge-previews"),
        ];
        for (heading, want) in cases {
            assert_eq!(github_slug(heading), want, "{heading}");
        }
    }

    #[test]
    fn readme_sections_parse() {
        let (sections, _) = parse_sections(README_MD);
        assert_eq!(sections[0].title, "Overview");
        let h2: Vec<&str> =
            sections.iter().filter(|s| s.level == 2).map(|s| s.title.as_str()).collect();
        // The README's top-level structure — update when sections are added.
        for want in [
            "Status",
            "Requirements",
            "Build & run",
            "Using it",
            "Data & locations",
            "CLI / diagnostics",
            "Widget inspector (F12)",
            "Architecture",
            "Roadmap",
        ] {
            assert!(h2.contains(&want), "missing ## section: {want}");
        }
        assert!(
            sections.iter().filter(|s| s.level == 3).count() >= 30,
            "expected the Using-it subsections to be split out"
        );
    }

    #[test]
    fn every_internal_anchor_resolves() {
        let (sections, anchors) = parse_sections(README_MD);
        let re = regex_lite::Regex::new(r"\]\(#([A-Za-z0-9_-]+)\)").unwrap();
        for cap in re.captures_iter(README_MD) {
            let anchor = format!("#{}", &cap[1]);
            let idx = anchors.get(&anchor);
            assert!(idx.is_some(), "README anchor {anchor} does not resolve to a section");
            let idx = *idx.unwrap();
            assert!(idx >= 1 && idx <= sections.len(), "anchor {anchor} → bad index {idx}");
        }
    }

    #[test]
    fn every_readme_image_is_embedded() {
        let re = regex_lite::Regex::new(r"\]\((doc/screenshots/[^)]+)\)").unwrap();
        for cap in re.captures_iter(README_MD) {
            let uri = format!("bytes://{}", &cap[1]);
            assert!(
                HELP_IMAGES.iter().any(|(u, _)| *u == uri),
                "README image {} is not embedded (build.rs help_images)",
                &cap[1]
            );
        }
        assert!(!HELP_IMAGES.is_empty());
    }

    #[test]
    fn fenced_fake_headings_are_ignored() {
        let md: &'static str = Box::leak(
            "intro\n```\n## fake heading\n```\n## Real\nbody\n".to_string().into_boxed_str(),
        );
        let (sections, _) = parse_sections(md);
        let titles: Vec<&str> = sections.iter().map(|s| s.title.as_str()).collect();
        assert_eq!(titles, vec!["Overview", "Real"]);
        assert!(sections[0].body.contains("## fake heading"));
    }

    #[test]
    fn tab_partition_shrinks_immediately_and_grows_with_hysteresis() {
        let w = [60.0, 60.0, 70.0, 50.0]; // 240 total
        let ovf = 30.0;
        // Everything fits.
        assert_eq!(super::super::partition_tabs(&w, 300.0, ovf, usize::MAX, 16.0), 4);
        // Nothing fits beside the overflow button.
        assert_eq!(super::super::partition_tabs(&w, 40.0, ovf, usize::MAX, 16.0), 0);
        // Partial: 60+60+30 <= 160, +70 would burst.
        assert_eq!(super::super::partition_tabs(&w, 160.0, ovf, usize::MAX, 16.0), 2);
        // Shrink applies immediately (prev said 4, now only 2 fit).
        assert_eq!(super::super::partition_tabs(&w, 160.0, ovf, 4, 16.0), 2);
        // Growth blocked inside the hysteresis band: 3 tabs + overflow = 220
        // fits a 230 budget, but not with 16 px spare → stay at 2.
        assert_eq!(super::super::partition_tabs(&w, 230.0, ovf, 2, 16.0), 2);
        // Growth allowed with real room.
        assert_eq!(super::super::partition_tabs(&w, 260.0, ovf, 2, 16.0), 4);
    }
}
